#!/bin/env zsh

# Control Borgbackup

export BORG_REPO=${BORG_REPO:-'/storage/backup/karsten'}
export BORG_PASSCOMMAND=${BORG_PASSCOMMAND:-'cat /home/karsten/.borgpass'}

prog_name=$(basename $0)
BACKUP_PROG=/usr/bin/borg
  
function sub_help(){
    echo "Usage: $prog_name <subcommand> [options]\n"
    echo "Subcommands:"
    echo "    \e[1;37m create \e[0m    Creates a new backup archive for today"
    echo "    \e[1;37m list   \e[0m    List archives"
    echo "    \e[1;37m restore <NAME>  \e[0m Mount archive <NAME> (usually in form a-YY-MM-dd) into ~/.restore"
    echo ""
    echo "For help with each subcommand run:"
    echo "$prog_name <subcommand> -h|--help"
    echo ""
    echo "Repository is set to \e[1;37m ${BORG_REPO} \e[0m"
    echo "Password command is  \e[1;37m '${BORG_PASSCOMMAND}' \e[0m"
}

function sub_create() {
    export ARCHIVE=$(date +'%a-%Y-%m-%d')
    $BACKUP_PROG create     \
        --verbose            \
        --filter AME         \
        --list               \
        --stats              \
        --show-rc            \
        --compression lz4    \
        --exclude-caches     \
        --exclude .venv      \
        --exclude .vagrant   \
        --exclude .pyc       \
        ::${ARCHIVE}         \
        /home

    $BACKUP_PROG prune     \
        --list              \
        --show-rc           \
        --keep-daily    7   \
        --keep-weekly   4   \
        --keep-monthly  6
}

function sub_list() {
    $BACKUP_PROG list
}

function sub_mount() {
    [ -d ~/.restore ] || mkdir ~/.restore
    $BACKUP_PROG mount $BORG_REPO::$1 ~/.restore
}


subcommand=$1
case $subcommand in
    "" | "-h" | "--help")
        sub_help
        ;;
    *)
        shift
        sub_${subcommand} $@
        if [ $? = 127 ]; then
            echo "Error: '$subcommand' is not a known subcommand." >&2
            echo "       Run '$prog_name --help' for a list of known subcommands." >&2
            exit 1
        fi
        ;;
esac
