[font]
size = 12.0
normal = { family = "Hack Nerd Font", style = "Regular" }

[window]
opacity = 0.9



[keyboard]
bindings = [
   { key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
   { key = ",", mods = "Control", action = "IncreaseFontSize" },
   { key = "R", mods = "Control|Shift", action = "ResetFontSize" },
   { key = "Enter", mods = "Control|Shift", action = "ToggleFullscreen" },
   { key = "Enter", mods = "Control", action = "ToggleMaximized" },
]

