
generate:
    @gpg --batch --generate-key gen-key-script

list:
    @gpg --list-keys

export key_id:
    @gpg --export --armor {{key_id}}

secret key_id:
    @gpg --export-secret-keys --armor {{key_id}}

