---
- name: Installiere Oh My Zsh und klone Dotfiles
  hosts: localhost

  vars:
    dotfile_repo: "https://github.com/kkroesch/dotfiles.git"
    public_ssh_key: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINJyFU5kpqGZeViom71S+3QMCIKWmSCMrUTrJKgm0vgF'

  tasks:

    - name: Klone Dotfiles in ein Bare-Repo
      git:
        repo: '{{ dotfile_repo }}'
        dest: /home/{{ ansible_user_id }}/.dotfiles
        bare: yes

    - name: Konfiguriere Git für das Bare-Repo
      shell: git --git-dir=/home/{{ ansible_user_id }}/.dotfiles/ --work-tree=/home/{{ ansible_user_id }} config --local status.showUntrackedFiles no

    - name: Checkout Dotfiles
      shell: git --git-dir=/home/{{ ansible_user_id }}/.dotfiles/ --work-tree=/home/{{ ansible_user_id }} checkout -f
      ignore_errors: yes

    - name: Neovim Plugins
      shell: curl -fLo /home/{{ ansible_user_id }}/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

    - name: Installiere Powerlevel10k Theme
      git:
        repo: https://github.com/romkatv/powerlevel10k.git
        dest: /home/{{ ansible_user_id }}/.oh-my-zsh/custom/themes/powerlevel10k

    - name: Setze Powerlevel10k Theme in .zshrc
      lineinfile:
        path: /home/{{ ansible_user_id }}/.zshrc
        regexp: '^ZSH_THEME='
        line: 'ZSH_THEME="powerlevel10k/powerlevel10k"'
        create: yes
          
    - name: Kopiere den öffentlichen SSH-Schlüssel in authorized_keys
      lineinfile:
        path: /home/{{ ansible_user_id }}/.ssh/authorized_keys
        line: "{{ public_ssh_key }}"
        create: yes
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        mode: '0600'


