---
- name: Retrieve SSH keys from gopass and store in .ssh directory
  hosts: localhost
  vars:
    gopass_entry: "path/to/ssh/key"
    ssh_dir: "{{ ansible_env.HOME }}/.ssh"
    private_key: "{{ lookup('pipe', 'gopass show ' + gopass_entry) }}"
    public_key: "{{ lookup('pipe', 'gopass show ' + gopass_entry + '.pub') }}"

  tasks:
    - name: Ensure .ssh directory exists
      file:
        path: "{{ ssh_dir }}"
        state: directory
        mode: '0700'

    - name: Write private key to .ssh directory
      copy:
        dest: "{{ ssh_dir }}/id_ed25519"
        content: "{{ private_key }}"
        mode: '0600'

    - name: Write public key to .ssh directory
      copy:
        dest: "{{ ssh_dir }}/id_ed25519.pub"
        content: "{{ public_key }}"
        mode: '0644'

